### ISSUE TITLE
Tvorba prezentace (5min) prvního sprint review

### ISSUE THREAD

**Issue by xverl00** [jirkae/hobby_hub#24]
Vytvořit 5ti minutovou prezentaci na první sprint review. Cílem je okomentovat backlog itemy (ty jsou pro MVP) a obsahy referencovaných issues (k nalezení dole)

**Comment by xverl00** [comment]
Výsledná prezentace
[Tým 3.pptx](https://github.com/jirkae/hobby_hub/files/533626/Tym.3.pptx)

**Comment by xmacm87** [comment]
PO poznámky - 
    super wireframe, občas trochu nepřehledné
    lean canvas - dobré, první nefér výhoda která dává smysl
    metriky - nedokážete to změřit, dobrý, ale chce to jasně stanovený cíl (jdu do toho nebo to zabalím)
    backlog je v pohodě
    super že kontroluje nejdřív teamleader, hezký že topujeme eventy
    výhrada - nebudeme pracovat o víkendu
