### ISSUE TITLE
Tvorba konceptuálního modelu dat

### ISSUE THREAD

**Issue by xverl00** [jirkae/hobby_hub#25]
Cílem je vytvořit konceptuální model dat pro MVP v jakémkoliv prostředí (třeba i powerdesigner) a vytvořit .png soubor jeho odrazu, který pošlete na #24 

Informace potřebné pro jeho zvládnutí berte z lean canvasu #23, balzamiq #27 a možná product backlogu (podle všeho byl revidován PO)

Hlavní body dle prezentace:
Attendee
	• Registrace a login
	• Editace profilu
	• Vyhledávání a filtrování akcí
	• Přihlášení na akci
	• Notifikace
	• Historie
Organizer
	• Založení akce a vyplnění detailu akce
	• Editace parametrů a zrušení akce
	• Akceptace účastníků akce
		○ Případné odmítnutí nebo odebrání
	• Hromadná notifikace všech účastníků akce
Druhy eventů:
	• Sporty všeho druhu
	• Turistika, vycházky se psem nebo kočárkem
	• Poker, společenské hry
	• Kultura, koncerty
	• Atd…

**Comment by xmacm87** [comment]
Přikládám obrázek modelu a zdorjové soubory do nástroje Astah:

![hobbyhub_v1](https://cloud.githubusercontent.com/assets/22476520/19385247/d654d3f6-920d-11e6-89fa-430c4190bce4.png)

**Comment by xmacm87** [comment]
Přikládám novou, aktualizovanou verzi doplněnou o další vlastnosti systému jako: Různé typy cen eventu a Ukládání zpráv posílaných uživatelem
[HobbyHub_v2.zip](https://github.com/jirkae/hobby_hub/files/531636/HobbyHub_v2.zip)
![hobbyhub_v2](https://cloud.githubusercontent.com/assets/22476520/19416172/a76efd6e-9389-11e6-9d90-263ef49abab9.png)

**Comment by xmacm87** [comment]
Aktualizovaná 2. verze. Zapracovány poznámky od PO
[HobbyHub_v2.zip](https://github.com/jirkae/hobby_hub/files/532034/HobbyHub_v2.zip)
![hobbyhub_v2](https://cloud.githubusercontent.com/assets/22476520/19419904/3ea9011e-93e1-11e6-8a42-2608bf7175cc.png)
