### ISSUE TITLE
Tvorba uživatelského rozhraní přes balzamiq

### ISSUE THREAD

**Issue by xverl00** [jirkae/hobby_hub#27]
Cílem je vytvořit uživatelské rozhraní v aplikaci Balzamiq (https://4it445.mybalsamiq.com/projects/tym3hobbyhub/grid ) tak, aby UI odpovídalo funkčním požadavkům na MVP (viz celý Product Backlog). Výsledek práce (pokud možno .png) by měl být v ideálním případě poslán do komentářů na #24

**Comment by JanHavel** [comment]
šablony pro inspiraci layoutem zde:
https://www.bootstrapzero.com

**Comment by JanHavel** [comment]
urbanj [12:06 PM]  
preferuju 5 poradne - respektive alespon ty ktere pokryjou hlavni featury - tedy vytvoreni eventu, vyhledani eventu, profil eventu a prihlasovani

[12:07]  
pokud bude 5 wireframu vsechny na login nebo registraci tak je to blbe, to znamena, pokryjte wireframy tu nejdulezitejsi funcionalitu.

**Comment by JanHavel** [comment]
1. verze k připomínkování
