### ISSUE TITLE
Bug: Psaní do search baru posouvá layout

### ISSUE THREAD

**Issue by xverl00** [jirkae/hobby_hub#69]
# Test scenario
1.  Kliknout na tab Výpis eventů
2. Do vyhledávače dej něco vyhledat
3. Search bar a samotné eventy se posunou vpravo
4. Vymazat text v search baru vrátí vše zpět

**Comment by JanHavel** [comment]
aktuální ?

**Comment by xverl00** [comment]
máš pravdu
