### ISSUE TITLE
Tvorba eventu - Projednat důležitost PSČ

### ISSUE THREAD

**Issue by xverl00** [jirkae/hobby_hub#85]
# Popis
Jaká je vůbec funkcionalita PSČ u eventu? Povinné pole to není, google s ním moc ani nepočítá. Zdá se mi jako zbytečný údaj

**Comment by JanHavel** [comment]
To bereš z te sablony ? 
Podle me je to tam jen jako mock a do finálu se s psč nepočítá.

**Comment by fixiee** [comment]
neni dulezite - odebrat

**Comment by JanHavel** [comment]
done ?

**Comment by xverl00** [comment]
jj
